### ISSUE TITLE
Get_punto() del triangolo

### ISSUE THREAD

**Issue by Teodoro777** [Teodoro777/Punto#2]
Il costruttore() e le set() dovrebbero andare, le get del triangolo non so se vanno bene..

**Comment by FabioZTessitore** [comment]
ovviamente no

**Comment by Teodoro777** [comment]
Uso le get di x e y di un punto?

**Comment by FabioZTessitore** [comment]
no, va bene dire che vuoi ritornare i vertici a, b e c, ma non è quello che fai. Leggi bene cosa hai scritto nel codice
